# Debian Trixie Release Countdown

theme: jekyll-theme-minimal
title: "ğŸ§ Debian Trixie ãƒªãƒªãƒ¼ã‚¹ã‚«ã‚¦ãƒ³ãƒˆãƒ€ã‚¦ãƒ³"
description: "Monitoring Debian feeds for the release of Trixie (Debian 13)"
